server: 
  port: 8081
  servlet: 
    context-path: /lsso-project-resource-server

####### resource server configuration properties
spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  devtools:
    livereload:
      port: 35730