spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            scope: user:email, read:user
            client-id: client-id
            client-secret: client-secret
    
server: 
  port: 8082
  servlet: 
    context-path: /lsso-client
    
logging: 
  level: 
    org.springframework: INFO