spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            scope: user:email, read:user
            client-id: 0b6c373a600c4856b03d
            client-secret: e66c3d38ae3f5d13580eff6d38fe2fffc7f249de
    
server: 
  port: 8082
  servlet: 
    context-path: /lsso-client
    
logging: 
  level: 
    org.springframework: INFO