server:
  port: 8083
spring:
  security:
    user:
      name: john@test.com
      password: $2a$10$yCl.WgsHZGpKeplZCVH1mea9IcCsbmLNXdbGJ511ws7AeyuLT6m9.
  devtools:
    livereload:
      port: 35731

security:
  oauth2:
    authorization:
      jwt:
        key-alias: mytest
        key-store: classpath:mytest.jks
        key-store-password: mypass
    client:
      client-id: lssoClient
      client-secret: lssoSecret
      scope:
        - read
        - write
      authorized-grant-types:
        - authorization_code
      registered-redirect-uri:
        - http://localhost:8082/lsso-client/login/oauth2/code/custom
      auto-approve-scopes:
        - read
        - write